title: Tatiana Gabel
logo: "1709892525258.jpg?raw=true"
description: >
  Computer Science Teacher
  <br><br>
  Colorado State University Computer and Data Science \n \n

  Motivated early professional with a Bachelor of Computer Science and hands-on experience in outreach and working with diverse students. Known for being people-oriented and taking initiative. Excited to support inclusive project-based learning





  
  <br><br>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0
